export const WORDS = [
  ["Anchorage International Airport", "ANC"],
  ["Phoenix, Phoenix Sky Harbor International Airport", "PHX"],
  ["Los Angeles International Airport", "LAX"],
  ["Oakland", "OAK"],
  ["Ontario", "ONT"],
  ["Sacramento", "SMF"],
  ["San Diego", "SAN"],
  ["San Francisco International Airport", "SFO"],
  ["San Jose", "SJC"],
  ["Santa Ana", "SNA"],
  ["Denver International Airport", "DEN"],
  ["Hartford", "BDL"],
  ["Washington, Dulles International Airport", "IAD"],
  ["Washington National Airport", "DCA"],
  ["Fort Lauderdale-Hollywood International Airport", "FLL"],
  ["Fort Meyers", "RSW"],
  ["Miami International Airport", "MIA"],
  ["Orlando", "MCO"],
  ["Tampa", "TPA"],
  ["Atlanta Hartsfield International Airport", "ATL"],
  ["Honolulu International Airport", "HNL"],
  ["Boise", "BOI"],
  ["Chicago Midway Airport", "MDW"],
  ["Chicago, O'Hare International Airport Airport", "ORD"],
  ["Indianapolis International Airport", "IND"],
  ["New Orleans International Airport", "MSY"],
  ["Baltimore", "BWI"],
  ["Boston, Logan International Airport", "BOS"],
  ["Detroit Metropolitan Airport", "DTW"],
  ["Minneapolis/St.Paul International Airport", "MSP"],
  ["Kansas City", "MCI"],
  ["St Louis, Lambert International Airport", "STL"],
  ["Omaha", "OMA"],
  ["Las Vegas, Las Vegas McCarran International Airport", "LAS"],
  ["Reno-Tahoe International Airport", "RNO"],
  ["Manchester", "MHT"],
  ["Atlantic City International Airport", "ACY"],
  ["Newark International Airport", "EWR"],
  ["Albuquerque International Airport", "ABQ"],
  ["New York, John F Kennedy International Airport", "JFK"],
  ["New York, La Guardia Airport", "LGA"],
  ["Charlotte/Douglas International Airport", "CLT"],
  ["Raleigh", "RDU"],
  ["Cincinnati", "CVG"],
  ["Cleveland", "CLE"],
  ["Columbus", "CMH"],
  ["Philadelphia", "PHL"],
  ["Pittsburgh", "PIT"],
  ["Memphis", "MEM"],
  ["Austin Bergstrom International Airport", "AUS"],
  ["Corpus Christi", "CRP"],
  ["Dallas Love Field Airport", "DAL"],
  ["Dallas/Fort Worth International Airport", "DFW"],
  ["Houston, William B Hobby Airport", "HOU"],
  ["Houston, George Bush Intercontinental Airport", "IAH"],
  ["San Antonio International Airport", "SAT"],
  ["Salt Lake City", "SLC"],
  ["Dulles", "IAD"],
  ["Seattle, Tacoma International Airport", "SEA"],
];
