export const wordsUpdated = [
  ["Abbotsford International Airport, YXX"],
  ["Abeid Amani Karume International Airport, ZNZ"],
  ["Abu Dhabi International Airport, AUH"],
  ["Addis Ababa Bole International Airport, ADD"],
  ["Adelaide International Airport, ADL"],
  ["Adnan Menderes International Airport, ADB"],
  ["Adolfo Suárez Madrid–Barajas Airport, MAD"],
  ["Al Maktoum International Airport, DWC"],
  ["Alejandro Velasco Astete International Airport, CUZ"],
  ["Alicante-Elche Miguel Hernández Airport, ALC"],
  ["Allama Iqbal International Airport, LHE"],
  ["Almaty International Airport, ALA"],
  ["Amsterdam Airport Schiphol, AMS"],
  ["Amílcar Cabral International Airport, SID"],
  ["Antalya International Airport, AYT"],
  ["Antonio B. Won Pat International Airport, GUM"],
  ["Ashgabat International Airport, ASB"],
  ["Athens Eleftherios Venizelos International Airport, ATH"],
  ["Auckland International Airport, AKL"],
  ["Austin Bergstrom International Airport, AUS"],
  ["Baghdad International Airport / New Al Muthana Air Base, BGW"],
  ["Bahrain International Airport, BAH"],
  ["Baltimore/Washington International Thurgood Marshall Airport, BWI"],
  ["Bandaranaike International Colombo Airport, CMB"],
  ["Banjul International Airport, BJL"],
  ["Bari Karol Wojtyła Airport, BRI"],
  ["Bauerfield International Airport, VLI"],
  ["Beijing Capital International Airport, PEK"],
  ["Beijing Daxing International Airport, PKX"],
  ["Beirut Rafic Hariri International Airport, BEY"],
  ["Belfast International Airport, BFS"],
  ["Belgrade Nikola Tesla Airport, BEG"],
  ["Ben Gurion International Airport, TLV"],
  ["Bergen Airport, Flesland, BGO"],
  ["Berlin Brandenburg Airport, BER"],
  ["Billund Airport, BLL"],
  ["Birmingham International Airport, BHX"],
  ["Blaise Diagne International Airport, DSS"],
  ["Bologna Guglielmo Marconi Airport, BLQ"],
  ["Bordeaux-Mérignac Airport, BOD"],
  ["Boryspil International Airport, KBP"],
  ["Brindisi Airport, BDS"],
  ["Brisbane International Airport, BNE"],
  ["Brunei International Airport, BWN"],
  ["Brussels Airport, BRU"],
  ["Budapest Liszt Ferenc International Airport, BUD"],
  ["Buffalo Niagara International Airport, BUF"],
  ["Burgas Airport, BOJ"],
  ["Cagliari Elmas Airport, CAG"],
  ["Cairo International Airport, CAI"],
  ["Calgary International Airport, YYC"],
  ["Cancún International Airport, CUN"],
  ["Cape Town International Airport, CPT"],
  ["Carrasco International /General C L Berisso Airport, MVD"],
  ["Catania-Fontanarossa Airport, CTA"],
  ["Cayenne – Félix Eboué Airport, CAY"],
  ["Changchun Longjia International Airport, CGQ"],
  ["Changsha Huanghua International Airport, CSX"],
  ["Charles de Gaulle International Airport, CDG"],
  ["Charlotte Douglas International Airport, CLT"],
  ["Chengdu Shuangliu International Airport, CTU"],
  ["Chengdu Tianfu International Airport, TFU"],
  ["Chennai International Airport, MAA"],
  ["Chhatrapati Shivaji International Airport, BOM"],
  ["Chiang Mai International Airport, CNX"],
  ["Chicago Midway International Airport, MDW"],
  ["Chicago O'Hare International Airport, ORD"],
  ["Chongqing Jiangbei International Airport, CKG"],
  ["Christchurch International Airport, CHC"],
  ["Chubu Centrair International Airport, NGO"],
  ["Cincinnati Northern Kentucky International Airport, CVG"],
  ["Cleveland Hopkins International Airport, CLE"],
  ["Cochin International Airport, COK"],
  ["Cologne Bonn Airport, CGN"],
  ["Comodoro Arturo Merino Benítez International Airport, SCL"],
  ["Copenhagen Kastrup Airport, CPH"],
  ["César Manrique-Lanzarote Airport, ACE"],
  ["Dabolim Airport, GOI"],
  ["Dalaman International Airport, DLM"],
  ["Dalian Zhoushuizi International Airport, DLC"],
  ["Dallas Fort Worth International Airport, DFW"],
  ["Damascus International Airport, DAM"],
  ["Daniel K Inouye International Airport, HNL"],
  ["Denver International Airport, DEN"],
  ["Deputado Luiz Eduardo Magalhães International Airport, SSA"],
  ["Detroit Metropolitan Wayne County Airport, DTW"],
  ["Diori Hamani International Airport, NIM"],
  ["Djibouti-Ambouli Airport, JIB"],
  ["Domodedovo International Airport, DME"],
  ["Don Miguel Hidalgo Y Costilla International Airport, GDL"],
  ["Don Mueang International Airport, DMK"],
  ["Dubai International Airport, DXB"],
  ["Dublin Airport, DUB"],
  ["Duqm International Airport, DQM"],
  ["Düsseldorf Airport, DUS"],
  ["Edinburgh Airport, EDI"],
  ["Edmonton International Airport, YEG"],
  ["Eduardo Gomes International Airport, MAO"],
  ["Eindhoven Airport, EIN"],
  ["El Dorado International Airport, BOG"],
  ["Entebbe International Airport, EBB"],
  ["Esenboğa International Airport, ESB"],
  ["EuroAirport Basel-Mulhouse-Freiburg Airport, BSL"],
  ["Faa'a International Airport, PPT"],
  ["Fairbanks International Airport, FAI"],
  ["Falcone–Borsellino Airport, PMO"],
  ["Faro Airport, FAO"],
  ["Flamingo International Airport, BON"],
  ["Fort Lauderdale Hollywood International Airport, FLL"],
  ["Francisco Bangoy International Airport, DVO"],
  ["Francisco de Sá Carneiro Airport, OPO"],
  ["Frankfurt am Main Airport, FRA"],
  ["Fuerteventura Airport, FUE"],
  ["Fukuoka Airport, FUK"],
  ["Fuzhou Changle International Airport, FOC"],
  ["Gagarin International Airport, GSV"],
  ["Gdańsk Lech Wałęsa Airport, GDN"],
  ["General Abelardo L. Rodríguez International Airport, TIJ"],
  ["General Ignacio P. Garcia International Airport, HMO"],
  ["General José Antonio Anzoategui International Airport, BLA"],
  ["General Juan N Alvarez International Airport, ACA"],
  ["General Mitchell International Airport, MKE"],
  ["General Rafael Buelna International Airport, MZT"],
  ["Geneva Cointrin International Airport, GVA"],
  ["George Bush Intercontinental Houston Airport, IAH"],
  ["Gimhae International Airport, PUS"],
  ["Gimpo International Airport, GMP"],
  ["Glasgow International Airport, GLA"],
  ["Gothenburg-Landvetter Airport, GOT"],
  ["Gran Canaria Airport, LPA"],
  ["Guanacaste Airport, LIR"],
  ["Guangzhou Baiyun International Airport, CAN"],
  ["Guarulhos - Governador André Franco Montoro International Airport, GRU"],
  ["Guilin Liangjiang International Airport, KWL"],
  ["Haikou Meilan International Airport, HAK"],
  ["Halifax / Stanfield International Airport, YHZ"],
  ["Hamad International Airport, DOH"],
  ["Hamburg Helmut Schmidt Airport, HAM"],
  ["Hangzhou Xiaoshan International Airport, HGH"],
  ["Hannover Airport, HAJ"],
  ["Harbin Taiping International Airport, HRB"],
  ["Hartsfield Jackson Atlanta International Airport, ATL"],
  ["Hasanuddin International Airport, UPG"],
  ["Hato International Airport, CUR"],
  ["Hazrat Shahjalal International Airport, DAC"],
  ["Hazrat Sultan International Airport, HSA"],
  ["Helsinki Vantaa Airport, HEL"],
  ["Henri Coandă International Airport, OTP"],
  ["Heraklion International Nikos Kazantzakis Airport, HER"],
  ["Hercílio Luz International Airport, FLN"],
  ["Hewanorra International Airport, UVF"],
  ["Heydar Aliyev International Airport, GYD"],
  ["Hohhot Baita International Airport, HET"],
  ["Hong Kong International Airport, HKG"],
  ["Honiara International Airport, HIR"],
  ["Hosea Kutako International Airport, WDH"],
  ["Houari Boumediene Airport, ALG"],
  ["Humberto Delgado Airport (Lisbon Portela Airport), LIS"],
  ["Hurghada International Airport, HRG"],
  ["Ibiza Airport, IBZ"],
  ["Imam Khomeini International Airport, IKA"],
  ["Incheon International Airport, ICN"],
  ["Indianapolis International Airport, IND"],
  ["Indira Gandhi International Airport, DEL"],
  ["Islamabad International Airport, ISB"],
  ["Istanbul Sabiha Gökçen International Airport, SAW"],
  ["Ivato Airport, TNR"],
  ["Jacksonville International Airport, JAX"],
  ["Jeju International Airport, CJU"],
  ["Jinan Yaoqiang International Airport, TNA"],
  ["Jinnah International Airport, KHI"],
  ["Johan Adolf Pengel International Airport, PBM"],
  ["John F Kennedy International Airport, JFK"],
  ["John Glenn Columbus International Airport, CMH"],
  ["John Wayne Airport-Orange County Airport, SNA"],
  ["Joint Base Andrews, ADW"],
  ["Jomo Kenyatta International Airport, NBO"],
  ["Jorge Chávez International Airport, LIM"],
  ["Jorge Newbery Airpark, AEP"],
  ["Josep Tarradellas Barcelona-El Prat Airport, BCN"],
  ["José Joaquín de Olmedo International Airport, GYE"],
  ["José Martí International Airport, HAV"],
  ["João Paulo II Airport, PDL"],
  ["Juan Gualberto Gomez International Airport, VRA"],
  ["Juanda International Airport, SUB"],
  ["Juba International Airport, JUB"],
  ["Julius Nyerere International Airport, DAR"],
  ["Kadena Air Base, DNA"],
  ["Kagoshima Airport, KOJ"],
  ["Kansai International Airport, KIX"],
  ["Kansas City International Airport, MCI"],
  ["Kaohsiung International Airport, KHH"],
  ["Kazan International Airport, KZN"],
  ["Keflavik International Airport, KEF"],
  ["Kempegowda International Airport, BLR"],
  ["Kenneth Kaunda International Airport, LUN"],
  ["Khartoum International Airport, KRT"],
  ["Kigali International Airport, KGL"],
  ["King Abdulaziz Air Base, DHA"],
  ["King Abdulaziz International Airport, JED"],
  ["King Fahd International Airport, DMM"],
  ["King Khaled International Airport, RUH"],
  ["King Mswati III International Airport, SHO"],
  ["King Shaka International Airport, DUR"],
  ["Koltsovo Airport, SVX"],
  ["Kotoka International Airport, ACC"],
  ["Kraków John Paul II International Airport, KRK"],
  ["Krasnoyarsk International Airport, KJA"],
  ["Kuala Lumpur International Airport, KUL"],
  ["Kunming Changshui International Airport, KMG"],
  ["Kurumoch International Airport, KUF"],
  ["Kuwait International Airport, KWI"],
  ["La Aurora Airport, GUA"],
  ["La Guardia Airport, LGA"],
  ["Lanzhou Zhongchuan International Airport, LHW"],
  ["Larnaca International Airport, LCA"],
  ["Las Américas International Airport, SDQ"],
  ["Leipzig/Halle Airport, LEJ"],
  ["Lennart Meri Tallinn Airport, TLL"],
  ["Lester B. Pearson International Airport, YYZ"],
  ["Licenciado Benito Juarez International Airport, MEX"],
  ["Ljubljana Jože Pučnik Airport, LJU"],
  ["Logan International Airport, BOS"],
  ["London Gatwick Airport, LGW"],
  ["London Heathrow Airport, LHR"],
  ["London Luton Airport, LTN"],
  ["London Stansted Airport, STN"],
  ["Longdongbao Airport, KWE"],
  ["Los Angeles International Airport, LAX"],
  ["Los Cabos International Airport, SJD"],
  ["Louis Armstrong New Orleans International Airport, MSY"],
  ["Louisville Muhammad Ali International Airport, SDF"],
  ["Luis Munoz Marin International Airport, SJU"],
  ["Lungi International Airport, FNA"],
  ["Luxembourg-Findel International Airport, LUX"],
  ["Lviv International Airport, LWO"],
  ["Lynden Pindling International Airport, NAS"],
  ["Lyon Saint-Exupéry Airport, LYS"],
  ["M. R. Štefánik Airport, BTS"],
  ["Macau International Airport, MFM"],
  ["Mactan Cebu International Airport, CEB"],
  ["Malpensa International Airport, MXP"],
  ["Malta International Airport, MLA"],
  ["Malé International Airport, MLE"],
  ["Manas International Airport, FRU"],
  ["Manchester Airport, MAN"],
  ["Mandalay International Airport, MDL"],
  ["Maputo Airport, MPM"],
  ["Mariscal Sucre International Airport, UIO"],
  ["Marseille Provence Airport, MRS"],
  ["Martinique Aimé Césaire International Airport, FDF"],
  ["Mashhad International Airport, MHD"],
  ["Mattala Rajapaksa International Airport, HRI"],
  ["McCarran International Airport, LAS"],
  ["Mehrabad International Airport, THR"],
  ["Melbourne International Airport, MEL"],
  ["Memphis International Airport, MEM"],
  ["Metropolitan Oakland International Airport, OAK"],
  ["Miami International Airport, MIA"],
  ["Milan Bergamo Airport, BGY"],
  ["Milas Bodrum International Airport, BJV"],
  ["Ministro Pistarini International Airport, EZE"],
  [
    "Minneapolis–Saint Paul International Airport / Wold–Chamberlain Field, MSP",
  ],
  ["Minsk National Airport, MSQ"],
  ["Modibo Keita International Airport, BKO"],
  ["Mohammed V International Airport, CMN"],
  ["Moi International Airport, MBA"],
  ["Monseñor Óscar Arnulfo Romero International Airport, SAL"],
  ["Montreal / Pierre Elliott Trudeau International Airport, YUL"],
  ["Muan International Airport, MWX"],
  ["Munich Airport, MUC"],
  ["Murtala Muhammed International Airport, LOS"],
  ["Muscat International Airport, MCT"],
  ["Málaga-Costa del Sol Airport, AGP"],
  ["N'Djamena International Airport, NDJ"],
  ["Naha Airport / JASDF Naha Air Base, OKA"],
  ["Nanchang Changbei International Airport, KHN"],
  ["Nanjing Lukou International Airport, NKG"],
  ["Nanning Wuxu Airport, NNG"],
  ["Naples International Airport, NAP"],
  ["Narita International Airport, NRT"],
  ["Nashville International Airport, BNA"],
  ["Ndjili International Airport, FIH"],
  ["Netaji Subhash Chandra Bose International Airport, CCU"],
  ["New Chitose Airport, CTS"],
  ["Newark Liberty International Airport, EWR"],
  ["Ngurah Rai (Bali) International Airport, DPS"],
  ["Nice-Côte d'Azur Airport, NCE"],
  ["Ningbo Lishe International Airport, NGB"],
  ["Ninoy Aquino International Airport, MNL"],
  ["Nnamdi Azikiwe International Airport, ABV"],
  ["Noi Bai International Airport, HAN"],
  ["Norman Manley International Airport, KIN"],
  ["Norman Y. Mineta San Jose International Airport, SJC"],
  ["Nouakchott–Oumtounsy International Airport, NKC"],
  ["Nouméa Magenta Airport, GEA"],
  ["Novosibirsk Tolmachevo Airport, OVB"],
  ["Nuremberg Airport, NUE"],
  ["Nursultan Nazarbayev International Airport, NQZ"],
  ["OR Tambo International Airport, JNB"],
  ["Ontario International Airport, ONT"],
  ["Orlando International Airport, MCO"],
  ["Orlando Sanford International Airport, SFB"],
  ["Osaka International Airport, ITM"],
  ["Oslo Airport, Gardermoen, OSL"],
  ["Ottawa Macdonald-Cartier International Airport, YOW"],
  ["Owen Roberts International Airport, GCM"],
  ["Palm Beach International Airport, PBI"],
  ["Palma de Mallorca Airport, PMI"],
  ["Paris-Orly Airport, ORY"],
  ["Perth International Airport, PER"],
  ["Philadelphia International Airport, PHL"],
  ["Philip S. W. Goldson International Airport, BZE"],
  ["Phnom Penh International Airport, PNH"],
  ["Phoenix Sky Harbor International Airport, PHX"],
  ["Phuket International Airport, HKT"],
  ["Pisa International Airport, PSA"],
  ["Pittsburgh International Airport, PIT"],
  ["Platov International Airport, ROV"],
  ["Podgorica Airport / Podgorica Golubovci Airbase, TGD"],
  ["Pointe-à-Pitre Le Raizet International  Airport, PTP"],
  ["Port Moresby Jacksons International Airport, POM"],
  ["Portland International Airport, PDX"],
  ["Portland International Jetport, PWM"],
  ["President Gustavo Díaz Ordaz International Airport, PVR"],
  ["Presidente Juscelino Kubitschek International Airport, BSB"],
  ["Prince Mohammad Bin Abdulaziz Airport, MED"],
  ["Princess Juliana International Airport, SXM"],
  ["Providenciales International Airport, PLS"],
  ["Pulkovo Airport, LED"],
  ["Punta Cana International Airport, PUJ"],
  ["Qingdao Jiaodong International Airport, TAO"],
  ["Quatro de Fevereiro International Airport, LAD"],
  ["Quebec Jean Lesage International Airport, YQB"],
  ["Queen Alia International Airport, AMM"],
  ["Queen Beatrix International Airport, AUA"],
  ["Rajiv Gandhi International Airport, HYD"],
  ["Raleigh Durham International Airport, RDU"],
  ["Ramon International Airport, ETM"],
  ["Reno Tahoe International Airport, RNO"],
  ["Richmond International Airport, RIC"],
  ["Riga International Airport, RIX"],
  ["Rio Galeão – Tom Jobim International Airport, GIG"],
  ["Robert Gabriel Mugabe International Airport, HRE"],
  ["Roberts International Airport, ROB"],
  ["Roland Garros Airport, RUN"],
  ["Rome–Fiumicino Leonardo da Vinci International Airport, FCO"],
  ["Ronald Reagan Washington National Airport, DCA"],
  ["Sacramento International Airport, SMF"],
  ["Salt Lake City International Airport, SLC"],
  ["San Antonio International Airport, SAT"],
  ["San Diego International Airport, SAN"],
  ["San Francisco International Airport, SFO"],
  [
    "Santa Lucía Air Force Base / General Felipe Ángeles International Airport, NLU",
  ],
  ["Santiago-Rosalía de Castro Airport, SCQ"],
  ["Sanya Phoenix International Airport, SYX"],
  ["Savannah Hilton Head International Airport, SAV"],
  ["Seattle Tacoma International Airport, SEA"],
  ["Sendai Airport, SDJ"],
  ["Sentani International Airport, DJJ"],
  ["Seychelles International Airport, SEZ"],
  ["Shanghai Hongqiao International Airport, SHA"],
  ["Shanghai Pudong International Airport, PVG"],
  ["Shannon Airport, SNN"],
  ["Sharjah International Airport, SHJ"],
  ["Sharm El Sheikh International Airport, SSH"],
  ["Shenyang Taoxian International Airport, SHE"],
  ["Shenzhen Bao'an International Airport, SZX"],
  ["Sheremetyevo International Airport, SVO"],
  ["Shiraz Shahid Dastghaib International Airport, SYZ"],
  ["Siem Reap International Airport, REP"],
  ["Simón Bolívar International Airport, CCS"],
  ["Singapore Changi Airport, SIN"],
  ["Sir Seewoosagur Ramgoolam International Airport, MRU"],
  ["Sir Seretse Khama International Airport, GBE"],
  ["Skopje International Airport, SKP"],
  ["Sochi International Airport, AER"],
  ["Soekarno-Hatta International Airport, CGK"],
  ["Sofia Airport, SOF"],
  ["Southwest Florida International Airport, RSW"],
  ["St Louis Lambert International Airport, STL"],
  ["St. John's International Airport, YYT"],
  ["Stavanger Airport, Sola, SVG"],
  ["Stockholm-Arlanda Airport, ARN"],
  ["Stuttgart Airport, STR"],
  ["Suvarnabhumi Airport, BKK"],
  ["Sydney Kingsford Smith International Airport, SYD"],
  ["Syracuse Hancock International Airport, SYR"],
  ["Taiwan Taoyuan International Airport, TPE"],
  ["Taiyuan Wusu Airport, TYN"],
  ["Tampa International Airport, TPA"],
  ["Tan Son Nhat International Airport, SGN"],
  ["Tancredo Neves International Airport, CNF"],
  ["Tashkent International Airport, TAS"],
  ["Tbilisi International Airport, TBS"],
  ["Ted Stevens Anchorage International Airport, ANC"],
  ["Tenerife Sur Airport, TFS"],
  ["Theodore Francis Green State Airport, PVD"],
  ["Thessaloniki Macedonia International Airport, SKG"],
  ["Tianjin Binhai International Airport, TSN"],
  ["Tirana International Airport Mother Teresa, TIA"],
  ["Tocumen International Airport, PTY"],
  ["Tokyo Haneda International Airport, HND"],
  ["Toulouse-Blagnac Airport, TLS"],
  ["Toussaint Louverture International Airport, PAP"],
  ["Tribhuvan International Airport, KTM"],
  ["Tripoli International Airport, TIP"],
  ["Trivandrum International Airport, TRV"],
  ["Tromsø Airport, Langnes, TOS"],
  ["Trondheim Airport, Værnes, TRD"],
  ["Tulsa International Airport, TUL"],
  ["Tunis Carthage International Airport, TUN"],
  ["Turin Airport, TRN"],
  ["Ufa International Airport, UFA"],
  ["Ulaanbaatar Chinggis Khaan International Airport, UBN"],
  ["Val de Cans/Júlio Cezar Ribeiro International Airport, BEL"],
  ["Vancouver International Airport, YVR"],
  ["Varna Airport, VAR"],
  ["Venice Marco Polo Airport, VCE"],
  ["Verona-Villafranca Valerio Catullo Airport, VRN"],
  ["Victoria International Airport, YYJ"],
  ["Vienna International Airport, VIE"],
  ["Vilnius International Airport, VNO"],
  ["Viru Viru International Airport, VVI"],
  ["Vladivostok International Airport, VVO"],
  ["Vnukovo International Airport, VKO"],
  ["Václav Havel Airport Prague, PRG"],
  ["Warsaw Chopin Airport, WAW"],
  ["Washington Dulles International Airport, IAD"],
  ["Wellington International Airport, WLG"],
  ["Wenzhou Longwan International Airport, WNZ"],
  ["Winnipeg / James Armstrong Richardson International Airport, YWG"],
  ["Wuhan Tianhe International Airport, WUH"],
  ["Xi'an Xianyang International Airport, XIY"],
  ["Xiamen Gaoqi International Airport, XMN"],
  ["Yangon International Airport, RGN"],
  ["Yantai Penglai International Airport, YNT"],
  ["Yokota Air Base, OKO"],
  ["Zagreb Airport, ZAG"],
  ["Zhengzhou Xinzheng International Airport, CGO"],
  ["Zhukovsky International Airport, ZIA"],
  ["Zvartnots International Airport, EVN"],
  ["Zürich Airport, ZRH"],
  ["Ürümqi Diwopu International Airport, URC"],
  ["İstanbul Airport, IST"],
  ["İstanbul Atatürk Airport, ISL"],
];
